baseurl: /
languageCode: en-us
title: Telling Stories with Data
theme: ath-tufte-hugo
googleAnalytics: ""
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - \.yaml$
  - _files$
  - _cache$
  - \.csl$
permalinks:
  post: "/:year/:month/:day/:slug/"
menu:
  main:
    - name: Syllabus
      url: /syllabus/
      weight: 1
    - name: Schedule
      url: /schedule/
      weight: 2
    - name: Assignments
      url: /assignments/
      weight: 3
    - name: Reference
      url: /reference/
      weight: 4
# Disable taxonomies
taxonomies:
  tag: ""
  group: ""
  category: ""
params:
  author: Andrew Heiss
  courseNumber: MPA 635
  description: A website built through Hugo and blogdown.
  logo:
    url: logo.png
    width: 50
    height: 50
    alt: Logo
