---
title: "Assignments"
slug: assignments
---

# Weekly reflection memo

You'll need to submit a one-page (500 words) reflection memo on Monday/Tuesday each week. You can do a lot of different things with this memo: discuss something you learned from the assigned blogs and podcasts that week, write about the best or worst presentation you saw that week, connect the readings or projects from that week to your own work, etc. These memos essentially let you explore and answer some of the key questions of this course, including:

-	Why do we give presentations about research?
-	What makes a presentation worth attending?
-	What are good visual aesthetics?
-	What makes a good visualization? What makes a bad visualization?
-	What is the role of stories in presenting analysis?
-	Why do people like stories?
-	What makes a good story? What makes a bad story?
-	What problems are there with framing scientific analysis as a story?
-	How comfortable should we be with uncertainty?
-	How can you lie with statistics? How do you tell the truth with statistics? 
-	How do you make sure people don’t think you’re lying with statistics?

These memos will only be graded for completion, and you’ll only need to complete X of the Y memos.

# Redesigns

In order to give you practice with the design and narrative principles you'll learn in this class, I will give you a series of slides, charts, and handouts that you will need to redesign (and possibly restructure). You will not need to create your own content for these assignments, though you are free (and encouraged) to recreate the content in whatever program you feel comfortable with. 

You'll get feedback about your first slide, chart, and handout redesign from your peers and from me, but they will only be graded for completion. The second slide, chart, and handout redesigns will be based on different content and will be graded (by me) according to a rubric I will provide.

# Story map

Each research presentation has a narrative structure that has to change depending on the medium and audience of the presentation. For this assignment, you will need to map out or outline narrative structures for multiple forms of an academic research article (which I will provide you). Map out the structure of the article itself and then create brief outlines for (1) a 12-minute presentation, (2) a 60-minute talk, (3) a policy brief, (4) an op-ed, (5) a blog post, and (6) a tweet.

# Presentation rubric

Evaluating presentations is hard. The slides have to be well designed, the content needs to be good, the narrative has to be coherent, and the delivery must be excellent. How do you know if a presentation does all that?!

Over the course of the semester, you will develop your own rubrics for evaluating the (1) content, (2) design, (3) narrative, and (4) delivery of a presentation, based on the readings, assignments, and classroom activities you'll do. These rubrics can take any form you want, as long as they include some approach for scoring performance and some method for quickly identifying specific areas of improvement. Where possible, try to cite the materials you draw from to create the rubric items.

Draft rubrics will be due at the end of each of the major course sections (conveniently indicated in the course schedule). You'll get feedback about these drafts from your peers and me, but they will only be graded for completion. I will grade your final combined rubric according to a rubric I will provide you.

# Rubric test run

Before you turn in your final rubric, you'll need to make sure it actually works. Use your improved draft rubrics to evaluate any presentation (a live one in another class, a TED talk, an extra on-campus seminar, etc.). You'll only be graded for completion.

# Final presentation

To evaluate how well you've learned the course materials, you will (1) give a 10 minute presentation and (2) create a 1-page handout (front and back allowed) about a research project (preferably your own research from another course, though you can also use an existing published article or study if needed). I will grade these final presentations according to both your rubric and my own rubric, with equal weight (i.e. your rubric score consists of 50% of the total grade). These presentations will be held during the course's scheduled final.
