---
title: "Effective visuals | Alignment, proximity | Typography"
date: "2017-11-01"
citeproc: false
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-fullnote-bibliography-no-bib.csl
---

# Required

- Chapter 2 in Cole Nussbaumer Knaflic, *Storytelling with Data* [@Knaflic:2015]
- [Engaging Readers with Square Pie/Waffle Charts](https://eagereyes.org/blog/2008/engaging-readers-with-square-pie-waffle-charts)
- [Understanding Pie Charts](https://eagereyes.org/techniques/pie-charts)
- [Square pie chart beats out the rest in perception study](https://flowingdata.com/2016/07/15/square-pie-chart-beats-out-the-rest-in-perception-study/)
- [Two Alternatives to Using a Second Y-Axis](http://stephanieevergreen.com/two-alternatives-to-using-a-second-y-axis/) & [Illusion of success](http://junkcharts.typepad.com/junk_charts/2006/06/illusion_of_suc.html) & [Dissecting two axes](http://junkcharts.typepad.com/junk_charts/2006/01/dissecting_two_.html)
- [Dual-Scaled Axes in Graphs: Are They Ever the Best Solution?](http://www.perceptualedge.com/articles/visual_business_intelligence/dual-scaled_axes.pdf) [@Few:2008]
- [The start-at-zero rule](http://junkcharts.typepad.com/junk_charts/2005/09/the_startatzero.html)


# Recommended

- Ian Spence, ["No Humble Pie: The Origins and Usage of a Statistical Chart"](http://www.psych.utoronto.ca/users/spence/Spence%202005.pdf) [@Spence:2005]
- Jeffrey Heer and Michael Bostock, ["Crowdsourcing Graphical Perception: Using Mechanical Turk to Assess Visualization Design"](http://vis.stanford.edu/papers/crowdsourcing-graphical-perception) [@HeerBostock:2010]
- Kieran Healy, ["Two y-axes"](https://kieranhealy.org/blog/archives/2016/01/16/two-y-axes/)
- ["A Study on Dual-Scale Data Charts"](https://www.lri.fr/~isenberg/publications/papers/Isenberg_2011_ASO.pdf) [@IsenbergBezerianosDragicevic:2011]


# Questions to reflect on

- How does the type of visualizations help or hinder our search for truth in data?
- Why are pie charts and curved lines generally unacceptable? When are pie and donut charts acceptable?
- How can you correctly and honestly communicate relationships between variables? How can you communicate the uncertainty in those relationships?
- When is it appropriate to use two y-axes?
- When is it okay (or not) to truncate the y-axis?
