---
title: "Heroes, myths, and journeys"
date: "2017-11-20"
due_date: "2017-11-20"
due_time: "11:59 AM"
---

# Get to know your article

Read through your assigned article at least once.


# Reflection memo

Write a 500-word memo about the assigned readings ([class 7](/reading/07-reading/); [class 8](/reading/08-reading/)) for this week. You can (should) use some of the prompt questions there if you want:

- How does structure contribute to a story's resonance and power?
- What is the role of drama in communicating science and research?
- What deeper social messages are communicated through stories like *Harry Potter* and *War and Peace*?
-	How can you know who your audience is? What if it's not a specific group of people that will be in a room? How do you tailor your stories to huge audiences (like in a blog post, op ed, or tweet?)
- How does viewing yourself as a mentor change your presentation style?
- How can you encourage audiences (i.e. the hero) to change?

As you write the memo, also consider these central questions:

- How do these readings connect to our main goal of discovering truth?
- How does what I just read apply to me?
- How can this be useful to me?

Submit the memo as "Reflection 4" on Learning Suite by noon on Monday.
